from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

def create_reference_template():
    doc = Document()
    
    # Title
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run('Saul Goodman: Strategy & Analysis')
    run.font.name = 'Times New Roman'
    run.font.size = Pt(24)
    run.bold = True
    
    tagline = doc.add_paragraph()
    tagline.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = tagline.add_run('Better Call Saul')
    run.font.name = 'Times New Roman'
    run.font.size = Pt(14)
    run.italic = True
    
    doc.add_paragraph('---' * 25)
    
    # Subject
    doc.add_heading('Subject: Financial Analysis of {{ company_name }}', level=2)
    
    # Executive Summary
    doc.add_heading('1. Executive Summary & Final Verdict', level=1)
    doc.add_paragraph('{{ final_summary }}')
    
    # KPIs
    doc.add_heading('2. Key Financial Metrics Extracted', level=1)
    doc.add_paragraph('The following key performance indicators were extracted from the financial documents:')
    
    # We use a table for KPIs in the reference template for better layout
    table = doc.add_table(rows=1, cols=2)
    table.style = 'Table Grid'
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Metric'
    hdr_cells[1].text = 'Value (Millions)'
    
    # Jinja2 loop for table rows
    # Note: docxtpl requires special handling for tables usually, but for simple rows:
    # We will put the loop inside the row definition in the template if possible, 
    # but python-docx doesn't let us write raw xml easily.
    # Instead, we'll just use the paragraph loop method which is safer for this simple generator.
    
    p = doc.add_paragraph()
    p.add_run('{% for key, value in kpi_data.items() %}')
    p.add_run('\n• ').bold = True
    p.add_run('{{ key }}: {{ value }}')
    p.add_run('{% endfor %}')
    
    # Debate
    doc.add_heading('3. The Boardroom: Analyst Debate Transcript', level=1)
    p = doc.add_paragraph()
    p.add_run('{% for entry in debate %}')
    p.add_run('\n\n{{ entry }}')
    p.add_run('{% endfor %}')
    
    doc.add_paragraph("\n" + "---" * 25)
    
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer.add_run("CONFIDENTIAL MEMORANDUM | Generated by the Saul Goodman Financial Strategy Assistant.")
    run.font.size = Pt(10)
    run.italic = True
    
    doc.save('backend/reference_template.docx')
    print("Created reference_template.docx")

if __name__ == "__main__":
    create_reference_template()
